-- V2: yaşa göre beceri maddeleri ve etkinlik kataloğu (uygulamayla aynı içerik)

insert into development_skill(area_id, code, text_tr, min_age_months, max_age_months) values
  (1, 's0', 'Tanıdık yetişkinden ayrılırken kısa sürede sakinleşiyor', 24, 48),
  (1, 's1', 'Başka çocukların yanında oynuyor (yan yana oyun)', 24, 42),
  (1, 's2', 'Tanıdık birine selam veriyor / el sallıyor', 24, 42),
  (1, 's3', 'Basit sıra alma oyunlarına katılıyor', 36, 60),
  (1, 's4', 'Bir arkadaşının adını söylüyor / arıyor', 36, 84),
  (1, 's5', 'Oyuncağını kısa süreliğine paylaşıyor', 36, 60),
  (1, 's6', 'Yardım istemek için yetişkine yöneliyor', 30, 60),
  (1, 's7', 'Grup içinde kendi sırasını bekliyor', 48, 84),
  (1, 's8', 'Bir arkadaşını oyuna davet ediyor', 48, 84),
  (1, 's9', 'Basit anlaşmazlığı vurmadan çözmeye çalışıyor', 54, 84),
  (1, 's10', 'Başkasının üzüldüğünü fark edip tepki veriyor', 48, 84),
  (2, 's11', '2-3 kelimelik cümleler kuruyor', 24, 42),
  (2, 's12', 'İsteğini kelimelerle ifade ediyor', 24, 48),
  (2, 's13', 'Tanıdık nesneleri adlandırıyor', 24, 42),
  (2, 's14', 'Basit bir olayı anlatıyor', 36, 60),
  (2, 's15', '“Ne, kim, nerede” sorularına cevap veriyor', 30, 54),
  (2, 's16', 'Konuşması aile dışındakiler tarafından anlaşılıyor', 36, 60),
  (2, 's17', '“Neden / nasıl” sorularına cevap veriyor', 48, 84),
  (2, 's18', 'Bir hikâyeyi sırasıyla anlatıyor', 54, 84),
  (2, 's19', 'Karşıt kavramları kullanıyor (büyük-küçük, uzun-kısa)', 42, 72),
  (2, 's20', 'Kendi adını ve yaşını söylüyor', 36, 60),
  (2, 's21', 'Kafiyeli kelimeleri fark ediyor', 60, 84),
  (3, 's22', 'Tek adımlı yönergeyi uyguluyor', 24, 42),
  (3, 's23', 'İki adımlı yönergeyi uyguluyor', 36, 60),
  (3, 's24', 'Üç adımlı yönergeyi uyguluyor', 60, 84),
  (3, 's25', 'Bir etkinlikte 5 dakika kalabiliyor', 30, 54),
  (3, 's26', 'Bir etkinlikte 10-15 dakika kalabiliyor', 54, 84),
  (3, 's27', 'Kısa bir hikâyeyi sonuna kadar dinliyor', 36, 72),
  (3, 's28', 'Bir etkinlikten diğerine geçerken zorlanmıyor', 36, 72),
  (3, 's29', 'Başladığı işi bitiriyor', 54, 84),
  (4, 's30', 'Kalemi tutup karalıyor', 24, 42),
  (4, 's31', 'Dikey ve yatay çizgi çiziyor', 30, 48),
  (4, 's32', 'Kule kuruyor (6+ blok)', 24, 48),
  (4, 's33', 'Daire çiziyor', 36, 54),
  (4, 's34', 'Kitabın sayfalarını tek tek çeviriyor', 24, 48),
  (4, 's35', 'Makasla çizgi üzerinde kesiyor', 48, 84),
  (4, 's36', 'İnsan figürü çiziyor (baş, gövde, kollar)', 48, 84),
  (4, 's37', 'Üçgen / kare kopyalıyor', 54, 84),
  (4, 's38', 'Adını yazmaya çalışıyor', 60, 84),
  (4, 's39', 'Kalemi üç parmakla tutuyor', 54, 84),
  (5, 's40', 'İki ayakla zıplıyor', 24, 42),
  (5, 's41', 'Koşarken yön değiştirebiliyor', 30, 54),
  (5, 's42', 'Merdiveni ayak değiştirerek çıkıyor', 36, 60),
  (5, 's43', 'Tek ayak üzerinde birkaç saniye duruyor', 36, 60),
  (5, 's44', 'Top atıp yakalıyor', 42, 84),
  (5, 's45', 'Tek ayakla sekiyor', 54, 84),
  (5, 's46', 'Üç tekerlekli bisiklet / kaydırak kullanıyor', 36, 72),
  (5, 's47', 'Çizgi üzerinde dengede yürüyor', 42, 84),
  (6, 's48', 'Renkleri eşleştiriyor', 24, 48),
  (6, 's49', 'Büyük parçalı yapbozu tamamlıyor', 30, 54),
  (6, 's50', '1-5 arası sayıyor', 36, 60),
  (6, 's51', 'Nesneleri özelliğine göre grupluyor', 42, 72),
  (6, 's52', 'Basit örüntüyü devam ettiriyor (kırmızı-mavi-kırmızı)', 48, 84),
  (6, 's53', '1-10 arası sayıp nesne sayısıyla eşleştiriyor', 54, 84),
  (6, 's54', 'Temel şekilleri tanıyor', 36, 72),
  (6, 's55', 'Dün-bugün-yarın kavramlarını kullanıyor', 54, 84),
  (6, 's56', 'Basit bir problemi deneyerek çözüyor', 42, 84),
  (6, 's57', 'Kendi adının ilk harfini tanıyor', 60, 84),
  (7, 's58', 'Yardımla el yıkıyor', 24, 42),
  (7, 's59', 'Kaşıkla kendi yiyor', 24, 48),
  (7, 's60', 'Bardaktan dökmeden içiyor', 24, 48),
  (7, 's61', 'Tuvalet ihtiyacını haber veriyor', 24, 48),
  (7, 's62', 'Tuvaletini büyük ölçüde bağımsız yapıyor', 42, 84),
  (7, 's63', 'Ayakkabısını giyiyor', 36, 60),
  (7, 's64', 'Montunu kendi giyiyor', 42, 72),
  (7, 's65', 'Düğme / fermuar ile baş ediyor', 48, 84),
  (7, 's66', 'Eşyalarını toplayıp yerine koyuyor', 42, 84),
  (7, 's67', 'Kendi çantasını hazırlıyor', 54, 84),
  (8, 's68', '-mış gibi oyun kuruyor', 30, 60),
  (8, 's69', 'Oyuncakları amacına uygun kullanıyor', 24, 48),
  (8, 's70', 'Bir oyunu 10 dakika sürdürüyor', 36, 72),
  (8, 's71', 'Kurallı oyuna katılıyor', 48, 84),
  (8, 's72', 'Rol dağıtarak birlikte oyun kuruyor', 54, 84),
  (8, 's73', 'Kaybetmeyi kabul edip oyuna devam ediyor', 60, 84),
  (9, 's74', 'Üzüldüğünde yetişkinden yardım istiyor', 24, 54),
  (9, 's75', 'Ağladıktan sonra kısa sürede sakinleşiyor', 24, 54),
  (9, 's76', 'Duygusunu adlandırıyor (üzgünüm, kızgınım)', 36, 72),
  (9, 's77', 'Küçük hayal kırıklıklarını kısa sürede atlatıyor', 42, 84),
  (9, 's78', 'Öfkelendiğinde sakinleşme yolu deniyor', 48, 84),
  (9, 's79', 'Beklemesi gerektiğinde kendini oyalayabiliyor', 48, 84),
  (9, 's80', 'Başkasının duygusunu tahmin ediyor', 54, 84)
on conflict (code) do nothing;

insert into activity(code, title_tr, area_code, min_age_months, max_age_months, goal_tr, materials_tr, duration_minutes, steps_tr, parent_tips_tr) values
  ('a1', 'Oyun hamuru fırını', 'ince', 24, 72, 'Parmak ve el kaslarını güçlendirmek, kalem tutuşunu hazırlamak.', array['Oyun hamuru','Plastik bıçak','Küçük kalıplar']::text[], 15, array['Hamuru birlikte yoğurun, elini iyice çalıştırsın.','Küçük toplar koparıp parmak uçlarıyla bastırsın.','Sosis şekli açıp plastik bıçakla dilimlesin.','"Fırın"a dizip sipariş oyunu oynayın.']::text[], array['Şeklin güzel olması değil, elin çalışması önemli.','Siz de kendi hamurunuzla yanında oynayın; yönlendirmek yerine eşlik edin.']::text[]),
  ('a2', 'Mandal yarışı', 'ince', 30, 72, 'Başparmak-işaret parmağı kavrayışını (kıskaç tutuş) desteklemek.', array['6-8 çamaşır mandalı','Bir karton kenarı ya da ip']::text[], 10, array['Mandalı iki parmakla açmayı gösterin.','Kartonun kenarına sırayla mandal takın.','Renk sırası verin: kırmızı-mavi-kırmızı.']::text[], array['Zorlanıyorsa daha yumuşak mandal seçin.','5-6 mandal yeterlidir; bitmeden sıkılırsa durun.']::text[]),
  ('a3', 'Boncuk dizme', 'ince', 30, 72, 'El-göz koordinasyonu ve iki elin birlikte çalışması.', array['İri boncuk veya makarna','Ayakkabı bağı / kalın ip']::text[], 12, array['İpin ucunu sertleştirin (bantlayın).','Önce serbest dizsin.','Sonra basit örüntü verin: uzun-kısa-uzun.']::text[], array['Küçük parçalar 3 yaş altı için uygun değildir, yanında olun.']::text[]),
  ('a4', 'Yırtma-yapıştırma kolajı', 'ince', 24, 66, 'Parmak gücü ve iki elin karşıt çalışması.', array['Eski dergi/renkli kâğıt','Yapıştırıcı','A4 kâğıt']::text[], 15, array['Kâğıtları birlikte yırtın.','Parçaları bir şekle (ağaç, balık) yapıştırın.','Bitince asın ve birlikte bakın.']::text[], array['Yırtma işini siz devralmayın; yavaş da olsa kendi yapsın.']::text[]),
  ('a5', 'Duygu kartları', 'duygu', 36, 84, 'Duyguyu tanıma ve adlandırma.', array['4 kâğıt','Kalem']::text[], 10, array['Birlikte 4 yüz çizin: mutlu, üzgün, kızgın, korkmuş.','Sırayla bir kart seçip o yüzü yapın.','"Ne zaman böyle hissettin?" diye sorun.']::text[], array['Cevabı düzeltmeyin, dinleyin.','Kendi gününüzden de bir örnek paylaşın.']::text[]),
  ('a6', 'Balon nefesi', 'duygu', 36, 84, 'Yoğun duygu anında sakinleşme yolu kazandırmak.', array['Yok']::text[], 5, array['Karnınıza elinizi koyun.','Burundan alıp karnı balon gibi şişirin.','Ağızdan yavaşça söndürün, 5 kez.']::text[], array['Kriz anında değil, sakin anlarda öğretin.','Günlük rutine (yatmadan önce) yerleştirin.']::text[]),
  ('a7', 'Sıra bekleme kulesi', 'sosyal', 36, 72, 'Sıra alma ve bekleme becerisi.', array['Bloklar veya bardaklar']::text[], 12, array['Sırayla birer blok koyarak kule yapın.','Sıra sizdeyken yüksek sesle "şimdi sıra bende" deyin.','Kule devrilince birlikte gülün, yeniden başlayın.']::text[], array['Devrilince tepkisini izleyin; hayal kırıklığını birlikte adlandırın.']::text[]),
  ('a8', 'Okul oyunu', 'sosyal', 30, 72, 'Okul rutinini oyunla tanıdık kılmak, kaygıyı azaltmak.', array['Oyuncak / peluş']::text[], 15, array['Peluşlar öğrenci, çocuğunuz öğretmen olsun.','Sabah gelme, ayrılma, oyun, yemek, alınma sırasını oynayın.','Ayrılık sahnesini mutlaka "geri gelme" ile bitirin.']::text[], array['Oyunda tekrarladığı sahne, en çok konuştuğu konudur; not alın.']::text[]),
  ('a9', 'Günün üç şeyi', 'dil', 36, 84, 'Anlatım ve olayları sıraya koyma.', array['Yok']::text[], 8, array['Eve dönüşte ya da yemekte sırayla anlatın.','"Önce ne oldu, sonra ne oldu?" diye sorun.','Siz de kendi gününüzden üç şey anlatın.']::text[], array['"Bugün ne yaptın?" yerine somut sorun: "Bahçede kiminle koştun?"']::text[]),
  ('a10', 'Resimden hikâye', 'dil', 42, 84, 'Cümle kurma, hikâye sırası.', array['Resimli kitap']::text[], 12, array['Yazıyı okumadan sadece resimlere bakın.','Her sayfada "burada ne oluyor?" diye sorun.','Sonunda hikâyeyi baştan birlikte anlatın.']::text[], array['Cümlesini tamamlamayın; bekleyin.']::text[]),
  ('a11', 'Basit yönerge oyunu', 'dikkat', 30, 72, 'Çok adımlı yönerge takibi ve dinleme.', array['Yok']::text[], 8, array['Tek adımla başlayın: "Yastığı bana getir."','İki adıma çıkın: "Önce ayakkabını al, sonra kapıya koy."','Başardıkça adım sayısını artırın.']::text[], array['Yönergeyi tekrar etmeden önce 5 saniye bekleyin.']::text[]),
  ('a12', 'Ne değişti?', 'dikkat', 42, 84, 'Görsel dikkat ve hatırlama.', array['5-6 küçük nesne','Bir örtü']::text[], 10, array['Nesneleri diziyin, 10 saniye baksın.','Gözünü kapatınca bir tanesini saklayın.','"Ne eksildi?" diye sorun, sonra sıra onda.']::text[], array['3 nesneyle başlayın, kolaylaştıkça artırın.']::text[]),
  ('a13', 'Kendi çantam', 'ozbakim', 36, 84, 'Bağımsızlık ve eşyalarını tanıma.', array['Okul çantası','Eşyalar']::text[], 10, array['Akşam çantayı birlikte hazırlayın, koyma işini o yapsın.','Her eşyayı adıyla söyleyin.','Sabah "çantanda ne var?" diye sorun.']::text[], array['Eksik kalsa da müdahale etmeyin; unutmak da öğrenmenin parçası.']::text[]),
  ('a14', 'Giyinme yarışı', 'ozbakim', 42, 84, 'Giyinme sırası ve bağımsızlık.', array['Mont, ayakkabı']::text[], 10, array['Montu yere serip "pelerin" yöntemiyle giymeyi gösterin.','Siz de yanında giyinin, kim önce biterse.','Ayakkabıda sağ-sol için içine işaret koyun.']::text[], array['Acele eden sabahlarda değil, hafta sonu deneyin.']::text[]),
  ('a15', 'Yastık parkuru', 'kaba', 24, 72, 'Denge, koordinasyon ve enerji boşaltma.', array['Yastıklar','Bant / ip']::text[], 15, array['Yastıkları basamak gibi dizin.','Bant çizgisinde düz yürüsün.','Sonda tek ayak üstünde 3 saniye dursun.']::text[], array['Okul dönüşü gerginlik varsa önce hareket, sonra sohbet.']::text[]),
  ('a16', 'Renk avı', 'bilis', 24, 60, 'Eşleştirme, gruplama, dikkat.', array['Renkli kâğıtlar']::text[], 10, array['Bir renk seçin, evde o renkten 5 şey bulun.','Bulduklarını yan yana dizip sayın.','Sonra "yumuşak olanlar" diye yeniden gruplayın.']::text[], array['Yanlış eşleştirmede düzeltmek yerine "birlikte bakalım" deyin.']::text[]),
  ('a17', 'Büyük parçalı yapboz', 'bilis', 24, 60, 'Görsel algı, parça-bütün ilişkisi, sabır.', array['6-12 parçalı yapboz']::text[], 15, array['Önce kenar parçalarını ayırın.','Resmin tamamını gösterip nereye ait olduğunu sorun.','Bitince birlikte ters çevirip yeniden yapın.']::text[], array['Takıldığında parçayı yerleştirmeyin, yönünü çevirmesini önerin.']::text[]),
  ('a18', 'Kutu şehri', 'oyun', 36, 84, 'Hayali oyun kurma ve birlikte oynama.', array['Karton kutular','Boya / bant']::text[], 20, array['Kutulardan ev, market, okul yapın.','Oyuncaklara rol verin.','Çocuğunuzun kurduğu senaryoyu siz takip edin.']::text[], array['Oyunu siz yönetmeyin; onun kurallarına uyun.']::text[]),
  ('a19', 'Sessiz-gürültülü oyunu', 'oyun', 36, 72, 'Kural takibi ve dürtü kontrolü.', array['Yok']::text[], 8, array['Müzik/alkış varken hareket, durunca heykel olun.','Rolleri değiştirin, komut onda olsun.']::text[], array['Kaybetme yok; oyun bitmeden durun.']::text[]),
  ('b1', 'Pipet kolyesi', 'ince', 36, 72, 'Kesme ve dizme becerisini birlikte çalıştırmak.', array['Renkli pipetler','Makas','İp']::text[], 12, array['Pipetleri birlikte 2-3 cm''lik parçalara kesin.','Parçaları ipe dizsin.','İki ucu bağlayıp kolye yapın.']::text[], array['Makası ilk kez kullanıyorsa elinizi elinin üstüne koyup eşlik edin.','Kesme yorucudur; 5-6 kesim yeterli.']::text[]),
  ('b2', 'Pamuk kulaklı resim', 'ince', 30, 60, 'Kıskaç tutuşu ve el-göz koordinasyonu.', array['Kulak temizleme çubuğu','Sulu boya','Kâğıt']::text[], 12, array['Çubuğu boyaya batırıp nokta nokta resim yapın.','Bir çiçek ya da ağaç çizip noktalarla doldurun.']::text[], array['Fırça yerine ince çubuk, parmak kaslarını daha çok çalıştırır.']::text[]),
  ('b3', 'Fasulye transferi', 'ince', 36, 72, 'İki el koordinasyonu ve kontrollü hareket.', array['İki kâse','Kuru fasulye / nohut','Kaşık ya da maşa']::text[], 10, array['Fasulyeleri kaşıkla bir kâseden diğerine taşısın.','Sonra maşayla deneyin, daha zordur.','Süre tutup oyuna çevirin.']::text[], array['Küçük parçalar 3 yaş altı için uygun değil; yanında kalın.']::text[]),
  ('b4', 'Bant labirenti', 'ince', 42, 84, 'El kontrolü ve planlama.', array['Kâğıt bandı','Zemin ya da masa']::text[], 15, array['Masaya bantla bir yol yapıştırın.','Arabayı yoldan çıkmadan sürsün.','Sonra bantları sökme işi de ona kalsın.']::text[], array['Bant sökmek parmak gücü için birebirdir; acele ettirmeyin.']::text[]),
  ('b5', 'Duygu termometresi', 'duygu', 48, 84, 'Duygunun şiddetini fark etmek ve adlandırmak.', array['Kâğıt','Kalem']::text[], 10, array['Kâğıda 1''den 5''e bir termometre çizin.','Gün içindeki bir anı seçip “kaçtaydın?” diye sorun.','Siz de kendi gününüzden bir an paylaşın.']::text[], array['Sayıyı düzeltmeyin; onun ölçüsü sizinkinden farklı olabilir.']::text[]),
  ('b6', 'Sakinleşme köşesi', 'duygu', 36, 84, 'Yoğun duyguda gidebileceği güvenli bir yer kurmak.', array['Yastık','Bir battaniye','2-3 sakin oyuncak']::text[], 15, array['Evin bir köşesini birlikte hazırlayın.','İsmini o koysun (“sakinlik yuvası”).','Sakin anlarda birlikte oturup deneyin.']::text[], array['Ceza yeri değildir; asla “git orada otur” diye gönderilmez.']::text[]),
  ('b7', 'Veda ritüeli kartı', 'duygu', 30, 72, 'Sabah ayrılığını tahmin edilebilir kılmak.', array['Küçük karton','Kalem']::text[], 10, array['Üç adımlık bir veda çizin: sarılma, öpücük, el sallama.','Kartı çantasına koyun.','Her sabah aynı sırayla uygulayın.']::text[], array['Ritüel kısa olsun; uzadıkça ayrılık zorlaşır.']::text[]),
  ('b8', 'Nefes çiçeği', 'duygu', 36, 72, 'Fizyolojik sakinleşmeyi öğretmek.', array['Yok (ya da gerçek bir çiçek)']::text[], 5, array['Çiçeği koklar gibi burundan nefes alın.','Mumu söndürür gibi ağızdan verin.','Beş kez tekrarlayın.']::text[], array['Kriz anında değil, sakin anlarda çalışın.']::text[]),
  ('b9', 'Kim ne sever?', 'sosyal', 48, 84, 'Başkasının bakış açısını fark etmek.', array['Yok']::text[], 10, array['Sırayla “annem en çok neyi sever?” diye tahmin edin.','Doğru tahminde alkışlayın.','Sınıftaki bir arkadaşı için de tahmin yürütün.']::text[], array['Yanlış tahminde düzeltmek yerine merak edin: “Neden öyle düşündün?”']::text[]),
  ('b10', 'Sıralı hikâye kartları', 'sosyal', 48, 84, 'Sosyal durumları konuşmak ve çözüm üretmek.', array['3-4 kâğıt','Kalem']::text[], 12, array['Basit bir sahne çizin: iki çocuk aynı oyuncağı istiyor.','“Şimdi ne olur?” diye sorun.','Farklı sonlar üretin, birlikte oynayın.']::text[], array['Doğru cevabı siz söylemeyin; seçenekleri çoğaltın.']::text[]),
  ('b11', 'Birlikte kule', 'sosyal', 30, 60, 'Ortak amaç ve sıra alma.', array['Bloklar']::text[], 10, array['Tek bir kuleyi sırayla yükseltin.','Her koyuşta ismini söyleyin: “sıra Ada''da”.','Devrilince birlikte gülün.']::text[], array['Yarış değil; ortak yapı olduğunu vurgulayın.']::text[]),
  ('b12', 'Misafir oyunu', 'sosyal', 42, 84, 'Selamlaşma, ikram, sohbet kalıpları.', array['Oyuncak çay takımı']::text[], 15, array['Peluşlar misafir olsun, kapıyı o açsın.','Karşılama cümlelerini deneyin.','Rolleri değiştirin, misafir o olsun.']::text[], array['Kalıpları tekrar ettikçe okulda da kullanmaya başlar.']::text[]),
  ('b13', 'Kelime torbası', 'dil', 36, 72, 'Adlandırma ve betimleme.', array['Bez torba','5-6 ev eşyası']::text[], 10, array['Torbadan bakmadan bir nesne çeksin.','Görmeden dokunup tahmin etsin.','Sonra o nesneyi üç kelimeyle anlatsın.']::text[], array['Tahmin yanlışsa ipucu verin, cevabı söylemeyin.']::text[]),
  ('b14', 'Telefon oyunu', 'dil', 36, 72, 'Sıra alarak konuşma ve dinleme.', array['İki oyuncak telefon ya da el']::text[], 8, array['Birbirinizi arayın, “alo” ile başlayın.','Günü anlatın, sonra kapatıp rolleri değiştirin.']::text[], array['Konuşma sırası size geçtiğinde kısa konuşun; alan bırakın.']::text[]),
  ('b15', 'Ne olurdu?', 'dil', 54, 84, 'Neden-sonuç düşüncesi ve uzun cümle kurma.', array['Yok']::text[], 10, array['“Yağmur hiç yağmasaydı ne olurdu?” gibi sorular sorun.','Cevabı birlikte uzatın.','Sıra onda; o da soru sorsun.']::text[], array['Mantık hatalarını düzeltmeyin; hayal kurmak amaç.']::text[]),
  ('b16', 'Şarkıda eksik kelime', 'dil', 30, 60, 'Dinleme, sözcük hatırlama, ses farkındalığı.', array['Bildiği bir şarkı']::text[], 8, array['Şarkıyı söylerken son kelimede durun.','Boşluğu o doldursun.','Sonra sıra sizde olsun.']::text[], array['Yavaş söyleyin; beklemek için 5 saniye tanıyın.']::text[]),
  ('b17', 'Heykel ol', 'dikkat', 36, 72, 'Dürtü kontrolü ve dinleme.', array['Müzik']::text[], 8, array['Müzik çalarken dans edin.','Durunca herkes heykel olsun.','Komutu vermeyi ona bırakın.']::text[], array['Eleme yok; oyun herkes eğlenirken bitsin.']::text[]),
  ('b18', 'Sesli arama', 'dikkat', 42, 84, 'Sürdürülmüş dikkat ve arama stratejisi.', array['Küçük bir nesne']::text[], 10, array['Nesneyi odada saklayın.','“Sıcak-soğuk” ile yönlendirin.','Sonra o saklasın, siz arayın.']::text[], array['Çok zorlanıyorsa alanı küçültün.']::text[]),
  ('b19', 'Beş dakikalık iş', 'dikkat', 48, 84, 'Başladığı işi bitirme alışkanlığı.', array['Kum saati ya da zamanlayıcı']::text[], 10, array['Küçük bir iş seçin: 6 çorabı eşleştirmek.','Zamanlayıcıyı kurun.','Bitince birlikte bakın, sonuca değil sürece bakın.']::text[], array['İş gerçekten kısa olsun; bitmeyen iş motivasyonu düşürür.']::text[]),
  ('b20', 'Hayvan yürüyüşü', 'kaba', 30, 72, 'Denge, güç ve beden farkındalığı.', array['Yok']::text[], 10, array['Ayı gibi yürüyün, kurbağa gibi zıplayın, yengeç gibi yan gidin.','Odanın bir ucundan diğerine geçin.','Hayvanı o seçsin.']::text[], array['Okul dönüşü gerginlik varsa önce hareket, sonra sohbet.']::text[]),
  ('b21', 'Balon havada', 'kaba', 30, 84, 'El-göz koordinasyonu ve takip.', array['Balon']::text[], 10, array['Balonu yere düşürmeden havada tutun.','Sadece elin tersiyle, sonra sadece kafayla deneyin.','Birlikte sayın.']::text[], array['Balon patlayabilir; parçalarını hemen toplayın.']::text[]),
  ('b22', 'Yastık parkuru II', 'kaba', 42, 84, 'Sıralı hareket planlama ve denge.', array['Yastık','İp','Sandalye']::text[], 15, array['Üç istasyonlu bir parkur kurun: tırman, geç, zıpla.','Sırayı sözlü tekrar etsin, sonra uygulasın.','Parkuru o yeniden tasarlasın.']::text[], array['Sırayı hatırlaması dikkat için de çalışır.']::text[]),
  ('b23', 'Örüntü treni', 'bilis', 48, 84, 'Örüntü kurma ve devam ettirme.', array['İki tür nesne (kapak, blok)']::text[], 12, array['Basit bir dizi kurun: kapak-blok-kapak.','Devamını getirsin.','Sonra kendi örüntüsünü kursun, siz devam edin.']::text[], array['İki öğeyle başlayın, kolaylaşınca üçe çıkın.']::text[]),
  ('b24', 'Mutfak sayımı', 'bilis', 36, 72, 'Sayma ile nesne sayısını eşleştirmek.', array['Çatal, kaşık, tabak']::text[], 10, array['Sofrayı birlikte kurun: “Kaç kişiyiz? Kaç tabak lazım?”','Sayarak alsın.','Eksik çıkarsa birlikte sayıp bulun.']::text[], array['Sayıları ezberletmek değil, nesneyle eşleştirmek önemli.']::text[]),
  ('b25', 'Gölge eşleştirme', 'bilis', 42, 72, 'Görsel algı ve şekil-zemin ayrımı.', array['Oyuncaklar','Kâğıt','Kalem']::text[], 12, array['Oyuncakların etrafını kâğıda çizin.','Her oyuncağı kendi gölgesine yerleştirsin.','Sayıyı artırarak zorlaştırın.']::text[], array['Okula hazırlıkta görsel algı için iyi bir temeldir.']::text[]),
  ('b26', 'Dün-bugün-yarın panosu', 'bilis', 54, 84, 'Zaman kavramı ve günü anlatma.', array['Kâğıt','Kalem']::text[], 10, array['Üç sütun çizin.','Her akşam bugüne bir şey çizsin.','Sabah “dün ne yaptık?” diye bakın.']::text[], array['Çizimin güzelliği değil, hatırlaması önemli.']::text[]),
  ('b27', 'Sabah sıra tablosu', 'ozbakim', 42, 84, 'Sabah rutinini bağımsız yürütmek.', array['Kâğıt','Kalem','Buzdolabı mıknatısı']::text[], 15, array['Sabahın 4 adımını birlikte çizin: kalk, giyin, kahvaltı, çanta.','Tabloyu göz hizasına asın.','Her adımda kendisi işaretlesin.']::text[], array['Hatırlatmayı siz değil tablo yapsın; bu bağımsızlığı büyütür.']::text[]),
  ('b28', 'Düğme tahtası', 'ozbakim', 48, 84, 'Giyinme becerisini giysiden bağımsız çalışmak.', array['Eski bir gömlek','Karton']::text[], 12, array['Gömleği kartona gerin.','Oturarak düğmeleri açıp kapatsın.','Sonra üstündeyken deneyin.']::text[], array['Sabah acelesinde değil, sakin bir vakitte çalışın.']::text[]),
  ('b29', 'Kendi suyum', 'ozbakim', 36, 72, 'Bağımsızlık ve kontrollü hareket.', array['Küçük sürahi','Bardak','Havlu']::text[], 8, array['Az su koyduğunuz sürahiyi ona verin.','Kendi bardağına doldursun.','Dökülürse havluyu o alsın.']::text[], array['Dökülmek öğrenmenin parçası; temizliği birlikte yapın.']::text[]),
  ('b30', 'Akşam çanta kontrolü', 'ozbakim', 48, 84, 'Sorumluluk ve eşyalarını yönetme.', array['Okul çantası']::text[], 8, array['Çantayı boşaltsın, içindekileri sayın.','Yarın için gerekenleri o koysun.','Kapağı kapatmak son adım olsun.']::text[], array['Unuttuğu bir şey olursa müdahale etmeyin; sonucu görmek öğretir.']::text[]),
  ('b31', 'Kutu ev', 'oyun', 30, 72, 'Hayali oyun ve mekân kurma.', array['Büyük karton kutu','Boya']::text[], 20, array['Kutuya kapı ve pencere açın.','Birlikte boyayın.','İçinde oynayacağı senaryoyu o kursun.']::text[], array['Kendi başına oynamak istediğinde çekilin; yalnız oyun da değerlidir.']::text[]),
  ('b32', 'Doktor çantası', 'oyun', 36, 72, 'Korkulan durumları oyunla işlemek.', array['Oyuncak doktor seti ya da bant, pamuk']::text[], 15, array['Peluşu muayene etsin.','Siz hasta olun, korkunuzu dile getirin.','Rolleri değiştirin.']::text[], array['Okula dair korkular da bu oyunda çıkabilir; dinleyin.']::text[]),
  ('b33', 'Kurallı zar oyunu', 'oyun', 54, 84, 'Kurala uyma ve kaybetmeyi taşıma.', array['Zar','Kâğıttan basit bir yol']::text[], 15, array['10 kareli bir yol çizin.','Sırayla zar atıp ilerleyin.','Oyun bitince kim kazandı diye konuşun.']::text[], array['Kaybedince üzülmesi normal; duyguyu adlandırın, oyunu bitirmeyin.']::text[]),
  ('b34', 'Yıldız çizgileri', 'ince', 60, 84, 'Okula hazırlıkta kalem kontrolü.', array['Kâğıt','Kalem']::text[], 10, array['Sayfaya noktalar koyun.','Noktaları birleştirsin.','Sonra kendi adının harflerini noktalarla yazıp birleştirsin.']::text[], array['Harf öğretmek amaç değil; kalem kontrolü çalışılıyor.']::text[]),
  ('b35', 'Ne değişti? (zor sürüm)', 'dikkat', 60, 84, 'Görsel dikkat ve çalışma belleği.', array['8-10 küçük nesne','Örtü']::text[], 10, array['Nesneleri dizin, 15 saniye baksın.','Bir tanesini değiştirin ya da yer değiştirin.','Ne değişti diye sorun.']::text[], array['Okula hazırlık döneminde dikkat süresi için iyi bir ölçü.']::text[]),
  ('b36', 'Sınıf kuralları panosu', 'sosyal', 54, 84, 'Grup kurallarını anlamak ve sahiplenmek.', array['Kâğıt','Kalem']::text[], 15, array['Okuldaki kuralları hatırlamaya çalışın.','Her kuralı bir resimle çizin.','Evde de üç kural belirleyip asın.']::text[], array['Kuralları o söylesin; yazdıran siz olun.']::text[])
on conflict (code) do nothing;
