/* ================= ALANLAR ================= */
const AREAS=[
 {c:"sosyal", n:"Sosyal-duygusal gelişim", k:"Sosyal", d:"Başkalarıyla ilişki kurma, paylaşma, gruba katılma."},
 {c:"dil",    n:"Dil ve iletişim",         k:"Dil",    d:"Kelime dağarcığı, cümle kurma, anlatma ve dinleme."},
 {c:"dikkat", n:"Dikkat ve yönerge takibi",k:"Dikkat", d:"Bir işte kalabilme, yönergeyi izleme, geçişlere uyum."},
 {c:"ince",   n:"İnce motor becerileri",   k:"İnce motor", d:"Parmak ve el kasları: kalem, makas, düğme."},
 {c:"kaba",   n:"Kaba motor becerileri",   k:"Kaba motor", d:"Denge, koşma, zıplama, top becerileri."},
 {c:"bilis",  n:"Bilişsel gelişim",        k:"Bilişsel", d:"Eşleştirme, sıralama, sayı ve kavramlar, problem çözme."},
 {c:"ozbakim",n:"Öz bakım ve bağımsızlık", k:"Öz bakım", d:"Yeme, giyinme, tuvalet, eşyalarını yönetme."},
 {c:"oyun",   n:"Oyun becerileri",         k:"Oyun",   d:"Hayali oyun, kurallı oyun, birlikte oynama."},
 {c:"duygu",  n:"Duygusal düzenleme",      k:"Duygu",  d:"Duyguyu tanıma, sakinleşme, hayal kırıklığını taşıma."}];
const AREA_N=Object.fromEntries(AREAS.map(a=>[a.c,a.n]));
const AREA_K=Object.fromEntries(AREAS.map(a=>[a.c,a.k]));
const AREA=Object.fromEntries(AREAS.map(a=>[a.c,a]));

const SCALE=["Çok zorlandı","Zorlandı","Biraz zorlandı","Kolay geçti"]; // index = değer 0..3

/* ================= GÜNLÜK MADDELER =================
   p: hangi evrede açılır — 1: gün 1-3 · 2: gün 4-7 · 3: 2. hafta · 4: 3. hafta ve sonrası */
const ITEMS=[
 {c:"evden",   t:"Evden çıkma",                     a:"duygu", p:1},
 {c:"ayrilik", t:"Ayrılık anındaki tepki",          a:"duygu", p:1},
 {c:"sakin",   t:"Ayrılıktan sonra sakinleşmesi",   a:"duygu", p:1,
   o:["Uzun sürdü","15-30 dakika","5-10 dakika","Hemen sakinleşti"]},
 {c:"destek",  t:"Öğretmenden destek kabul etmesi", a:"sosyal",p:1,
   o:["Kabul etmedi","Zor kabul etti","Bir süre sonra kabul etti","Rahatça kabul etti"]},
 {c:"oyun",    t:"Oyuna katılım",                   a:"oyun",  p:1},
 {c:"yemek",   t:"Yemek",                           a:"ozbakim",p:1},
 {c:"uyku",    t:"Uyku / dinlenme",                 a:"ozbakim",p:1},
 {c:"donus",   t:"Eve dönüşteki duygu durumu",      a:"duygu", p:1,
   o:["Çok yorgun/üzgündü","Durgundu","İyiydi","Neşeliydi"]},

 {c:"ogrt",    t:"Öğretmenle ilişkisi",             a:"sosyal",p:2},
 {c:"rutin",   t:"Sınıf rutinlerine katılım",       a:"dikkat",p:2},
 {c:"yonerge", t:"Yönerge takibi",                  a:"dikkat",p:2},
 {c:"etkinlik",t:"Etkinliklere katılım",            a:"bilis", p:2},
 {c:"akranilgi",t:"Akranlarına ilgisi",             a:"sosyal",p:2},
 {c:"sabah",   t:"Sabah hazırlığı (kalkma, giyinme)",a:"ozbakim",p:2},

 {c:"aidiyet", t:"Okula aidiyet duygusu",           a:"sosyal",p:3},
 {c:"guven",   t:"Öğretmene güven",                 a:"sosyal",p:3},
 {c:"giris",   t:"Sınıfa isteyerek girmesi",        a:"sosyal",p:3},
 {c:"secme",   t:"Kendi etkinliğini seçmesi",       a:"oyun",  p:3},
 {c:"akran",   t:"Akran etkileşimi",                a:"sosyal",p:3},
 {c:"duyguduz",t:"Gün içinde duygularını düzenlemesi",a:"duygu",p:3},
 {c:"konusma", t:"Sınıfta konuşması / istek belirtmesi",a:"dil",p:3},

 {c:"ozbakim", t:"Öz bakım (el yıkama, giyinme)",   a:"ozbakim",p:4},
 {c:"tuvalet", t:"Tuvalet ihtiyacını haber vermesi",a:"ozbakim",p:4},
 {c:"bagimsiz",t:"Bağımsız hareket etmesi",         a:"ozbakim",p:4},
 {c:"esya",    t:"Eşyalarını tanıması ve toplaması",a:"bilis", p:4},
 {c:"sira",    t:"Sıra bekleme",                    a:"sosyal",p:4},
 {c:"paylasma",t:"Oyuncak paylaşması",              a:"sosyal",p:4},
 {c:"gecis",   t:"Geçişlere uyum (etkinlikten etkinliğe)",a:"dikkat",p:4},
 {c:"hayal",   t:"Küçük hayal kırıklıklarını tolere etmesi",a:"duygu",p:4},
 {c:"anlatim", t:"Okulda olanları anlatması",       a:"dil",   p:4},
 {c:"enerji",  t:"Eve döndüğünde enerjisi",         a:"kaba",  p:4,
   o:["Tükenmiş görünüyordu","Çok yorgundu","Biraz yorgundu","Dinç görünüyordu"]}
];
const ITEM=Object.fromEntries(ITEMS.map(i=>[i.c,i]));
const MOODS=[{v:4,e:"😊",t:"Rahat geçti"},{v:3,e:"🙂",t:"Genel olarak iyiydi"},
             {v:2,e:"😐",t:"Biraz zorlandı"},{v:1,e:"😢",t:"Zor bir gündü"}];

const LEVELS=[
 {c:"IND", t:"Bağımsız yapıyor",       v:3},
 {c:"REM", t:"Hatırlatmayla yapıyor",  v:2},
 {c:"HELP",t:"Yardımla yapıyor",       v:1},
 {c:"NOT", t:"Henüz yapmıyor",         v:0},
 {c:"NA",  t:"Gözlemleme fırsatım olmadı", v:null}];
const LEVEL=Object.fromEntries(LEVELS.map(l=>[l.c,l]));

/* ================= 30 GÜNLÜK OKULA UYUM YOLCULUĞU ================= */
const PHASES=[
 {p:1,g:"1-3. gün",  b:"Ayrılık ve ilk temas",
  o:"İlk günlerde tek ölçü ayrılık anı değil; çocuğunuzun ayrıldıktan sonra ne kadar sürede sakinleştiği ve gün içinde oyuna dönüp dönmediği daha çok şey anlatır.",
  t:["Evden çıkma","Ayrılık tepkisi","Sakinleşme süresi","Öğretmenden destek kabulü","Oyuna katılım","Yemek","Uyku","Eve dönüş duygu durumu"]},
 {p:2,g:"4-7. gün",  b:"Öğretmen ve sınıf rutini",
  o:"Bu günlerde çocuk ortamı tanımaya başlar. Öğretmenle kurulan bağ, ayrılığın kolaylaşmasının en güçlü habercisidir.",
  t:["Öğretmenle ilişki","Sınıf rutinleri","Yönerge takibi","Etkinliklere katılım","Akranlara ilgi","Sabah hazırlığı"]},
 {p:3,g:"2. hafta",  b:"Aidiyet ve güven",
  o:"İkinci haftada “buraya aitim” hissi belirmeye başlar. Sınıfa isteyerek girme ve kendi etkinliğini seçme bunun işaretleridir.",
  t:["Okula aidiyet","Öğretmene güven","Sınıfa isteyerek giriş","Etkinlik seçme","Akran etkileşimi","Duygusal düzenleme","Sınıfta konuşma"]},
 {p:4,g:"3-4. hafta",b:"Bağımsızlık ve grup",
  o:"Son haftalarda odak öz bakım ve grup içinde hareket edebilmeye kayar. 30. günde ilk aylık özetiniz hazır olur.",
  t:["Öz bakım","Tuvalet","Bağımsızlık","Eşyalarını tanıma","Sıra bekleme","Paylaşma","Geçişlere uyum","Hayal kırıklığı toleransı","Anlatım"]}];

/* Günlük kısa ipucu — kaygı üretmeyen, uygulanabilir, tek cümlelik. */
const TIPS={
 1:"Vedalaşma kısa ve net olsun: “Öpücük, sonra görüşürüz, seni almaya geleceğim.” Gizlice çıkmak ertesi günü zorlaştırır.",
 2:"Ağlamak uyumsuzluk değil, ayrılığa verilen sağlıklı bir tepkidir. Önemli olan sonrasında sakinleşebilmesi.",
 3:"Öğretmene “ne kadar sürede sakinleşti?” diye sorun. Bu, kapıdaki görüntüden daha çok şey anlatır.",
 4:"Aynı vedalaşma cümlesini her gün tekrarlayın; tahmin edilebilirlik güven verir.",
 5:"Eve dönüşte hemen soru sormayın. Önce 15 dakika sessizce yanında olun.",
 6:"Okuldan bahsederken “korkma, alışırsın” yerine “zor gelmiş olabilir, yanındayım” deyin.",
 7:"İlk hafta bitti. Bugün yalnızca iyi giden bir şeyi fark edin ve ona söyleyin.",
 8:"Sabahları 10 dakika erken kalkmak, acele etmeden çıkmayı sağlar; acele ayrılığı zorlaştırır.",
 9:"Çantasını akşamdan birlikte hazırlayın; koyma işini o yapsın.",
 10:"Evde “okulcuk” oynayın. Ayrılık sahnesini mutlaka geri gelme ile bitirin.",
 11:"Öğretmenin adını evde sık kullanın; tanıdıklık bağı güçlendirir.",
 12:"Bir arkadaşının adını öğrenin ve evde ondan konuşun.",
 13:"Hafta sonu okul rutinine benzer bir uyku saatini koruyun.",
 14:"İki hafta doldu. Bu iyi bir an: ilk günle bugünü kıyaslayın, kendi ilerlemesini görün.",
 15:"Sınıfa girerken bir “geçiş nesnesi” (küçük bir mendil, resim) yardımcı olabilir.",
 16:"Yemekte zorlanma sıksa evde baskı kurmayın; masaya birlikte oturmak yeterli.",
 17:"Öğretmeninize gözlem bağlantısı gönderin; iki gözlemi yan yana görmek çok şey açıklar.",
 18:"Gün içinde iki seçenek sunun (“mavi mi kırmızı mont mu?”); küçük kontrol duygusu kaygıyı azaltır.",
 19:"“Bugün ne yaptın?” yerine somut sorun: “Bahçede kiminle koştun?”",
 20:"Öfke ya da ağlama akşamları artabilir; gün boyu tutulan duygu evde boşalır, bu beklenendir.",
 21:"Üçüncü hafta: öz bakıma odaklanın. Ayakkabısını kendi giymesi için 5 dakika erken başlayın.",
 22:"Sıra bekleme evde de öğrenilir: sırayla blok koyarak kule yapın.",
 23:"Eşyalarına isim/işaret koyun; kendi çantasını tanımak bağımsızlığı besler.",
 24:"Hayal kırıklığını adlandırın: “Kule devrildi, buna çok üzüldün.” Düzeltmeden önce duyguyu karşılayın.",
 25:"Geçişler zorsa önceden haber verin: “Beş dakika sonra toplayacağız.”",
 26:"Bugün hiçbir şey sormayın, sadece birlikte oynayın. İlişki en iyi onarımdır.",
 27:"Okulda çekilen bir resmi buzdolabına asın; okul ile ev arasında köprü kurar.",
 28:"Dördüncü hafta: ilk aylık özetiniz yaklaşıyor. Kayıt girmediğiniz günler varsa sorun değil.",
 29:"Yarın bir ay doluyor. Bu ay en çok neyin değiştiğini bir cümleyle kendinize yazın.",
 30:"Bir ay tamamlandı. Aylık özetiniz hazır — güçlü yanlarla başlayın."};

/* ================= YAŞA UYGUN BECERİLER =================
   [alan, metin, min ay, max ay] */
const SKILLS=[
 // Sosyal-duygusal
 ["sosyal","Tanıdık yetişkinden ayrılırken kısa sürede sakinleşiyor",24,48],
 ["sosyal","Başka çocukların yanında oynuyor (yan yana oyun)",24,42],
 ["sosyal","Tanıdık birine selam veriyor / el sallıyor",24,42],
 ["sosyal","Basit sıra alma oyunlarına katılıyor",36,60],
 ["sosyal","Bir arkadaşının adını söylüyor / arıyor",36,84],
 ["sosyal","Oyuncağını kısa süreliğine paylaşıyor",36,60],
 ["sosyal","Yardım istemek için yetişkine yöneliyor",30,60],
 ["sosyal","Grup içinde kendi sırasını bekliyor",48,84],
 ["sosyal","Bir arkadaşını oyuna davet ediyor",48,84],
 ["sosyal","Basit anlaşmazlığı vurmadan çözmeye çalışıyor",54,84],
 ["sosyal","Başkasının üzüldüğünü fark edip tepki veriyor",48,84],
 // Dil ve iletişim
 ["dil","2-3 kelimelik cümleler kuruyor",24,42],
 ["dil","İsteğini kelimelerle ifade ediyor",24,48],
 ["dil","Tanıdık nesneleri adlandırıyor",24,42],
 ["dil","Basit bir olayı anlatıyor",36,60],
 ["dil","“Ne, kim, nerede” sorularına cevap veriyor",30,54],
 ["dil","Konuşması aile dışındakiler tarafından anlaşılıyor",36,60],
 ["dil","“Neden / nasıl” sorularına cevap veriyor",48,84],
 ["dil","Bir hikâyeyi sırasıyla anlatıyor",54,84],
 ["dil","Karşıt kavramları kullanıyor (büyük-küçük, uzun-kısa)",42,72],
 ["dil","Kendi adını ve yaşını söylüyor",36,60],
 ["dil","Kafiyeli kelimeleri fark ediyor",60,84],
 // Dikkat ve yönerge
 ["dikkat","Tek adımlı yönergeyi uyguluyor",24,42],
 ["dikkat","İki adımlı yönergeyi uyguluyor",36,60],
 ["dikkat","Üç adımlı yönergeyi uyguluyor",60,84],
 ["dikkat","Bir etkinlikte 5 dakika kalabiliyor",30,54],
 ["dikkat","Bir etkinlikte 10-15 dakika kalabiliyor",54,84],
 ["dikkat","Kısa bir hikâyeyi sonuna kadar dinliyor",36,72],
 ["dikkat","Bir etkinlikten diğerine geçerken zorlanmıyor",36,72],
 ["dikkat","Başladığı işi bitiriyor",54,84],
 // İnce motor
 ["ince","Kalemi tutup karalıyor",24,42],
 ["ince","Dikey ve yatay çizgi çiziyor",30,48],
 ["ince","Kule kuruyor (6+ blok)",24,48],
 ["ince","Daire çiziyor",36,54],
 ["ince","Kitabın sayfalarını tek tek çeviriyor",24,48],
 ["ince","Makasla çizgi üzerinde kesiyor",48,84],
 ["ince","İnsan figürü çiziyor (baş, gövde, kollar)",48,84],
 ["ince","Üçgen / kare kopyalıyor",54,84],
 ["ince","Adını yazmaya çalışıyor",60,84],
 ["ince","Kalemi üç parmakla tutuyor",54,84],
 // Kaba motor
 ["kaba","İki ayakla zıplıyor",24,42],
 ["kaba","Koşarken yön değiştirebiliyor",30,54],
 ["kaba","Merdiveni ayak değiştirerek çıkıyor",36,60],
 ["kaba","Tek ayak üzerinde birkaç saniye duruyor",36,60],
 ["kaba","Top atıp yakalıyor",42,84],
 ["kaba","Tek ayakla sekiyor",54,84],
 ["kaba","Üç tekerlekli bisiklet / kaydırak kullanıyor",36,72],
 ["kaba","Çizgi üzerinde dengede yürüyor",42,84],
 // Bilişsel
 ["bilis","Renkleri eşleştiriyor",24,48],
 ["bilis","Büyük parçalı yapbozu tamamlıyor",30,54],
 ["bilis","1-5 arası sayıyor",36,60],
 ["bilis","Nesneleri özelliğine göre grupluyor",42,72],
 ["bilis","Basit örüntüyü devam ettiriyor (kırmızı-mavi-kırmızı)",48,84],
 ["bilis","1-10 arası sayıp nesne sayısıyla eşleştiriyor",54,84],
 ["bilis","Temel şekilleri tanıyor",36,72],
 ["bilis","Dün-bugün-yarın kavramlarını kullanıyor",54,84],
 ["bilis","Basit bir problemi deneyerek çözüyor",42,84],
 ["bilis","Kendi adının ilk harfini tanıyor",60,84],
 // Öz bakım
 ["ozbakim","Yardımla el yıkıyor",24,42],
 ["ozbakim","Kaşıkla kendi yiyor",24,48],
 ["ozbakim","Bardaktan dökmeden içiyor",24,48],
 ["ozbakim","Tuvalet ihtiyacını haber veriyor",24,48],
 ["ozbakim","Tuvaletini büyük ölçüde bağımsız yapıyor",42,84],
 ["ozbakim","Ayakkabısını giyiyor",36,60],
 ["ozbakim","Montunu kendi giyiyor",42,72],
 ["ozbakim","Düğme / fermuar ile baş ediyor",48,84],
 ["ozbakim","Eşyalarını toplayıp yerine koyuyor",42,84],
 ["ozbakim","Kendi çantasını hazırlıyor",54,84],
 // Oyun
 ["oyun","-mış gibi oyun kuruyor",30,60],
 ["oyun","Oyuncakları amacına uygun kullanıyor",24,48],
 ["oyun","Bir oyunu 10 dakika sürdürüyor",36,72],
 ["oyun","Kurallı oyuna katılıyor",48,84],
 ["oyun","Rol dağıtarak birlikte oyun kuruyor",54,84],
 ["oyun","Kaybetmeyi kabul edip oyuna devam ediyor",60,84],
 // Duygusal düzenleme
 ["duygu","Üzüldüğünde yetişkinden yardım istiyor",24,54],
 ["duygu","Ağladıktan sonra kısa sürede sakinleşiyor",24,54],
 ["duygu","Duygusunu adlandırıyor (üzgünüm, kızgınım)",36,72],
 ["duygu","Küçük hayal kırıklıklarını kısa sürede atlatıyor",42,84],
 ["duygu","Öfkelendiğinde sakinleşme yolu deniyor",48,84],
 ["duygu","Beklemesi gerektiğinde kendini oyalayabiliyor",48,84],
 ["duygu","Başkasının duygusunu tahmin ediyor",54,84]
].map((s,i)=>({c:"s"+i,a:s[0],t:s[1],min:s[2],max:s[3]}));

/* ================= ETKİNLİK KATALOĞU ================= */
const ACTS_BASE=[
 {c:"a1",a:"ince",t:"Oyun hamuru fırını",min:24,max:72,dk:15,
  g:"Parmak ve el kaslarını güçlendirmek, kalem tutuşunu hazırlamak.",
  m:["Oyun hamuru","Plastik bıçak","Küçük kalıplar"],
  s:["Hamuru birlikte yoğurun, elini iyice çalıştırsın.","Küçük toplar koparıp parmak uçlarıyla bastırsın.","Sosis şekli açıp plastik bıçakla dilimlesin.","\"Fırın\"a dizip sipariş oyunu oynayın."],
  d:["Şeklin güzel olması değil, elin çalışması önemli.","Siz de kendi hamurunuzla yanında oynayın; yönlendirmek yerine eşlik edin."]},
 {c:"a2",a:"ince",t:"Mandal yarışı",min:30,max:72,dk:10,
  g:"Başparmak-işaret parmağı kavrayışını (kıskaç tutuş) desteklemek.",
  m:["6-8 çamaşır mandalı","Bir karton kenarı ya da ip"],
  s:["Mandalı iki parmakla açmayı gösterin.","Kartonun kenarına sırayla mandal takın.","Renk sırası verin: kırmızı-mavi-kırmızı."],
  d:["Zorlanıyorsa daha yumuşak mandal seçin.","5-6 mandal yeterlidir; bitmeden sıkılırsa durun."]},
 {c:"a3",a:"ince",t:"Boncuk dizme",min:30,max:72,dk:12,
  g:"El-göz koordinasyonu ve iki elin birlikte çalışması.",
  m:["İri boncuk veya makarna","Ayakkabı bağı / kalın ip"],
  s:["İpin ucunu sertleştirin (bantlayın).","Önce serbest dizsin.","Sonra basit örüntü verin: uzun-kısa-uzun."],
  d:["Küçük parçalar 3 yaş altı için uygun değildir, yanında olun."]},
 {c:"a4",a:"ince",t:"Yırtma-yapıştırma kolajı",min:24,max:66,dk:15,
  g:"Parmak gücü ve iki elin karşıt çalışması.",
  m:["Eski dergi/renkli kâğıt","Yapıştırıcı","A4 kâğıt"],
  s:["Kâğıtları birlikte yırtın.","Parçaları bir şekle (ağaç, balık) yapıştırın.","Bitince asın ve birlikte bakın."],
  d:["Yırtma işini siz devralmayın; yavaş da olsa kendi yapsın."]},
 {c:"a5",a:"duygu",t:"Duygu kartları",min:36,max:84,dk:10,
  g:"Duyguyu tanıma ve adlandırma.",
  m:["4 kâğıt","Kalem"],
  s:["Birlikte 4 yüz çizin: mutlu, üzgün, kızgın, korkmuş.","Sırayla bir kart seçip o yüzü yapın.","\"Ne zaman böyle hissettin?\" diye sorun."],
  d:["Cevabı düzeltmeyin, dinleyin.","Kendi gününüzden de bir örnek paylaşın."]},
 {c:"a6",a:"duygu",t:"Balon nefesi",min:36,max:84,dk:5,
  g:"Yoğun duygu anında sakinleşme yolu kazandırmak.",
  m:["Yok"],
  s:["Karnınıza elinizi koyun.","Burundan alıp karnı balon gibi şişirin.","Ağızdan yavaşça söndürün, 5 kez."],
  d:["Kriz anında değil, sakin anlarda öğretin.","Günlük rutine (yatmadan önce) yerleştirin."]},
 {c:"a7",a:"sosyal",t:"Sıra bekleme kulesi",min:36,max:72,dk:12,
  g:"Sıra alma ve bekleme becerisi.",
  m:["Bloklar veya bardaklar"],
  s:["Sırayla birer blok koyarak kule yapın.","Sıra sizdeyken yüksek sesle \"şimdi sıra bende\" deyin.","Kule devrilince birlikte gülün, yeniden başlayın."],
  d:["Devrilince tepkisini izleyin; hayal kırıklığını birlikte adlandırın."]},
 {c:"a8",a:"sosyal",t:"Okul oyunu",min:30,max:72,dk:15,
  g:"Okul rutinini oyunla tanıdık kılmak, kaygıyı azaltmak.",
  m:["Oyuncak / peluş"],
  s:["Peluşlar öğrenci, çocuğunuz öğretmen olsun.","Sabah gelme, ayrılma, oyun, yemek, alınma sırasını oynayın.","Ayrılık sahnesini mutlaka \"geri gelme\" ile bitirin."],
  d:["Oyunda tekrarladığı sahne, en çok konuştuğu konudur; not alın."]},
 {c:"a9",a:"dil",t:"Günün üç şeyi",min:36,max:84,dk:8,
  g:"Anlatım ve olayları sıraya koyma.",
  m:["Yok"],
  s:["Eve dönüşte ya da yemekte sırayla anlatın.","\"Önce ne oldu, sonra ne oldu?\" diye sorun.","Siz de kendi gününüzden üç şey anlatın."],
  d:["\"Bugün ne yaptın?\" yerine somut sorun: \"Bahçede kiminle koştun?\""]},
 {c:"a10",a:"dil",t:"Resimden hikâye",min:42,max:84,dk:12,
  g:"Cümle kurma, hikâye sırası.",
  m:["Resimli kitap"],
  s:["Yazıyı okumadan sadece resimlere bakın.","Her sayfada \"burada ne oluyor?\" diye sorun.","Sonunda hikâyeyi baştan birlikte anlatın."],
  d:["Cümlesini tamamlamayın; bekleyin."]},
 {c:"a11",a:"dikkat",t:"Basit yönerge oyunu",min:30,max:72,dk:8,
  g:"Çok adımlı yönerge takibi ve dinleme.",
  m:["Yok"],
  s:["Tek adımla başlayın: \"Yastığı bana getir.\"","İki adıma çıkın: \"Önce ayakkabını al, sonra kapıya koy.\"","Başardıkça adım sayısını artırın."],
  d:["Yönergeyi tekrar etmeden önce 5 saniye bekleyin."]},
 {c:"a12",a:"dikkat",t:"Ne değişti?",min:42,max:84,dk:10,
  g:"Görsel dikkat ve hatırlama.",
  m:["5-6 küçük nesne","Bir örtü"],
  s:["Nesneleri diziyin, 10 saniye baksın.","Gözünü kapatınca bir tanesini saklayın.","\"Ne eksildi?\" diye sorun, sonra sıra onda."],
  d:["3 nesneyle başlayın, kolaylaştıkça artırın."]},
 {c:"a13",a:"ozbakim",t:"Kendi çantam",min:36,max:84,dk:10,
  g:"Bağımsızlık ve eşyalarını tanıma.",
  m:["Okul çantası","Eşyalar"],
  s:["Akşam çantayı birlikte hazırlayın, koyma işini o yapsın.","Her eşyayı adıyla söyleyin.","Sabah \"çantanda ne var?\" diye sorun."],
  d:["Eksik kalsa da müdahale etmeyin; unutmak da öğrenmenin parçası."]},
 {c:"a14",a:"ozbakim",t:"Giyinme yarışı",min:42,max:84,dk:10,
  g:"Giyinme sırası ve bağımsızlık.",
  m:["Mont, ayakkabı"],
  s:["Montu yere serip \"pelerin\" yöntemiyle giymeyi gösterin.","Siz de yanında giyinin, kim önce biterse.","Ayakkabıda sağ-sol için içine işaret koyun."],
  d:["Acele eden sabahlarda değil, hafta sonu deneyin."]},
 {c:"a15",a:"kaba",t:"Yastık parkuru",min:24,max:72,dk:15,
  g:"Denge, koordinasyon ve enerji boşaltma.",
  m:["Yastıklar","Bant / ip"],
  s:["Yastıkları basamak gibi dizin.","Bant çizgisinde düz yürüsün.","Sonda tek ayak üstünde 3 saniye dursun."],
  d:["Okul dönüşü gerginlik varsa önce hareket, sonra sohbet."]},
 {c:"a16",a:"bilis",t:"Renk avı",min:24,max:60,dk:10,
  g:"Eşleştirme, gruplama, dikkat.",
  m:["Renkli kâğıtlar"],
  s:["Bir renk seçin, evde o renkten 5 şey bulun.","Bulduklarını yan yana dizip sayın.","Sonra \"yumuşak olanlar\" diye yeniden gruplayın."],
  d:["Yanlış eşleştirmede düzeltmek yerine \"birlikte bakalım\" deyin."]},
 {c:"a17",a:"bilis",t:"Büyük parçalı yapboz",min:24,max:60,dk:15,
  g:"Görsel algı, parça-bütün ilişkisi, sabır.",
  m:["6-12 parçalı yapboz"],
  s:["Önce kenar parçalarını ayırın.","Resmin tamamını gösterip nereye ait olduğunu sorun.","Bitince birlikte ters çevirip yeniden yapın."],
  d:["Takıldığında parçayı yerleştirmeyin, yönünü çevirmesini önerin."]},
 {c:"a18",a:"oyun",t:"Kutu şehri",min:36,max:84,dk:20,
  g:"Hayali oyun kurma ve birlikte oynama.",
  m:["Karton kutular","Boya / bant"],
  s:["Kutulardan ev, market, okul yapın.","Oyuncaklara rol verin.","Çocuğunuzun kurduğu senaryoyu siz takip edin."],
  d:["Oyunu siz yönetmeyin; onun kurallarına uyun."]},
 {c:"a19",a:"oyun",t:"Sessiz-gürültülü oyunu",min:36,max:72,dk:8,
  g:"Kural takibi ve dürtü kontrolü.",
  m:["Yok"],
  s:["Müzik/alkış varken hareket, durunca heykel olun.","Rolleri değiştirin, komut onda olsun."],
  d:["Kaybetme yok; oyun bitmeden durun."]}
];
const ACTS_EXTRA=[
 {c:"b1",a:"ince",t:"Pipet kolyesi",min:36,max:72,dk:12,
  g:"Kesme ve dizme becerisini birlikte çalıştırmak.",
  m:["Renkli pipetler","Makas","İp"],
  s:["Pipetleri birlikte 2-3 cm'lik parçalara kesin.","Parçaları ipe dizsin.","İki ucu bağlayıp kolye yapın."],
  d:["Makası ilk kez kullanıyorsa elinizi elinin üstüne koyup eşlik edin.","Kesme yorucudur; 5-6 kesim yeterli."]},
 {c:"b2",a:"ince",t:"Pamuk kulaklı resim",min:30,max:60,dk:12,
  g:"Kıskaç tutuşu ve el-göz koordinasyonu.",
  m:["Kulak temizleme çubuğu","Sulu boya","Kâğıt"],
  s:["Çubuğu boyaya batırıp nokta nokta resim yapın.","Bir çiçek ya da ağaç çizip noktalarla doldurun."],
  d:["Fırça yerine ince çubuk, parmak kaslarını daha çok çalıştırır."]},
 {c:"b3",a:"ince",t:"Fasulye transferi",min:36,max:72,dk:10,
  g:"İki el koordinasyonu ve kontrollü hareket.",
  m:["İki kâse","Kuru fasulye / nohut","Kaşık ya da maşa"],
  s:["Fasulyeleri kaşıkla bir kâseden diğerine taşısın.","Sonra maşayla deneyin, daha zordur.","Süre tutup oyuna çevirin."],
  d:["Küçük parçalar 3 yaş altı için uygun değil; yanında kalın."]},
 {c:"b4",a:"ince",t:"Bant labirenti",min:42,max:84,dk:15,
  g:"El kontrolü ve planlama.",
  m:["Kâğıt bandı","Zemin ya da masa"],
  s:["Masaya bantla bir yol yapıştırın.","Arabayı yoldan çıkmadan sürsün.","Sonra bantları sökme işi de ona kalsın."],
  d:["Bant sökmek parmak gücü için birebirdir; acele ettirmeyin."]},

 {c:"b5",a:"duygu",t:"Duygu termometresi",min:48,max:84,dk:10,
  g:"Duygunun şiddetini fark etmek ve adlandırmak.",
  m:["Kâğıt","Kalem"],
  s:["Kâğıda 1'den 5'e bir termometre çizin.","Gün içindeki bir anı seçip “kaçtaydın?” diye sorun.","Siz de kendi gününüzden bir an paylaşın."],
  d:["Sayıyı düzeltmeyin; onun ölçüsü sizinkinden farklı olabilir."]},
 {c:"b6",a:"duygu",t:"Sakinleşme köşesi",min:36,max:84,dk:15,
  g:"Yoğun duyguda gidebileceği güvenli bir yer kurmak.",
  m:["Yastık","Bir battaniye","2-3 sakin oyuncak"],
  s:["Evin bir köşesini birlikte hazırlayın.","İsmini o koysun (“sakinlik yuvası”).","Sakin anlarda birlikte oturup deneyin."],
  d:["Ceza yeri değildir; asla “git orada otur” diye gönderilmez."]},
 {c:"b7",a:"duygu",t:"Veda ritüeli kartı",min:30,max:72,dk:10,
  g:"Sabah ayrılığını tahmin edilebilir kılmak.",
  m:["Küçük karton","Kalem"],
  s:["Üç adımlık bir veda çizin: sarılma, öpücük, el sallama.","Kartı çantasına koyun.","Her sabah aynı sırayla uygulayın."],
  d:["Ritüel kısa olsun; uzadıkça ayrılık zorlaşır."]},
 {c:"b8",a:"duygu",t:"Nefes çiçeği",min:36,max:72,dk:5,
  g:"Fizyolojik sakinleşmeyi öğretmek.",
  m:["Yok (ya da gerçek bir çiçek)"],
  s:["Çiçeği koklar gibi burundan nefes alın.","Mumu söndürür gibi ağızdan verin.","Beş kez tekrarlayın."],
  d:["Kriz anında değil, sakin anlarda çalışın."]},

 {c:"b9",a:"sosyal",t:"Kim ne sever?",min:48,max:84,dk:10,
  g:"Başkasının bakış açısını fark etmek.",
  m:["Yok"],
  s:["Sırayla “annem en çok neyi sever?” diye tahmin edin.","Doğru tahminde alkışlayın.","Sınıftaki bir arkadaşı için de tahmin yürütün."],
  d:["Yanlış tahminde düzeltmek yerine merak edin: “Neden öyle düşündün?”"]},
 {c:"b10",a:"sosyal",t:"Sıralı hikâye kartları",min:48,max:84,dk:12,
  g:"Sosyal durumları konuşmak ve çözüm üretmek.",
  m:["3-4 kâğıt","Kalem"],
  s:["Basit bir sahne çizin: iki çocuk aynı oyuncağı istiyor.","“Şimdi ne olur?” diye sorun.","Farklı sonlar üretin, birlikte oynayın."],
  d:["Doğru cevabı siz söylemeyin; seçenekleri çoğaltın."]},
 {c:"b11",a:"sosyal",t:"Birlikte kule",min:30,max:60,dk:10,
  g:"Ortak amaç ve sıra alma.",
  m:["Bloklar"],
  s:["Tek bir kuleyi sırayla yükseltin.","Her koyuşta ismini söyleyin: “sıra Ada'da”.","Devrilince birlikte gülün."],
  d:["Yarış değil; ortak yapı olduğunu vurgulayın."]},
 {c:"b12",a:"sosyal",t:"Misafir oyunu",min:42,max:84,dk:15,
  g:"Selamlaşma, ikram, sohbet kalıpları.",
  m:["Oyuncak çay takımı"],
  s:["Peluşlar misafir olsun, kapıyı o açsın.","Karşılama cümlelerini deneyin.","Rolleri değiştirin, misafir o olsun."],
  d:["Kalıpları tekrar ettikçe okulda da kullanmaya başlar."]},

 {c:"b13",a:"dil",t:"Kelime torbası",min:36,max:72,dk:10,
  g:"Adlandırma ve betimleme.",
  m:["Bez torba","5-6 ev eşyası"],
  s:["Torbadan bakmadan bir nesne çeksin.","Görmeden dokunup tahmin etsin.","Sonra o nesneyi üç kelimeyle anlatsın."],
  d:["Tahmin yanlışsa ipucu verin, cevabı söylemeyin."]},
 {c:"b14",a:"dil",t:"Telefon oyunu",min:36,max:72,dk:8,
  g:"Sıra alarak konuşma ve dinleme.",
  m:["İki oyuncak telefon ya da el"],
  s:["Birbirinizi arayın, “alo” ile başlayın.","Günü anlatın, sonra kapatıp rolleri değiştirin."],
  d:["Konuşma sırası size geçtiğinde kısa konuşun; alan bırakın."]},
 {c:"b15",a:"dil",t:"Ne olurdu?",min:54,max:84,dk:10,
  g:"Neden-sonuç düşüncesi ve uzun cümle kurma.",
  m:["Yok"],
  s:["“Yağmur hiç yağmasaydı ne olurdu?” gibi sorular sorun.","Cevabı birlikte uzatın.","Sıra onda; o da soru sorsun."],
  d:["Mantık hatalarını düzeltmeyin; hayal kurmak amaç."]},
 {c:"b16",a:"dil",t:"Şarkıda eksik kelime",min:30,max:60,dk:8,
  g:"Dinleme, sözcük hatırlama, ses farkındalığı.",
  m:["Bildiği bir şarkı"],
  s:["Şarkıyı söylerken son kelimede durun.","Boşluğu o doldursun.","Sonra sıra sizde olsun."],
  d:["Yavaş söyleyin; beklemek için 5 saniye tanıyın."]},

 {c:"b17",a:"dikkat",t:"Heykel ol",min:36,max:72,dk:8,
  g:"Dürtü kontrolü ve dinleme.",
  m:["Müzik"],
  s:["Müzik çalarken dans edin.","Durunca herkes heykel olsun.","Komutu vermeyi ona bırakın."],
  d:["Eleme yok; oyun herkes eğlenirken bitsin."]},
 {c:"b18",a:"dikkat",t:"Sesli arama",min:42,max:84,dk:10,
  g:"Sürdürülmüş dikkat ve arama stratejisi.",
  m:["Küçük bir nesne"],
  s:["Nesneyi odada saklayın.","“Sıcak-soğuk” ile yönlendirin.","Sonra o saklasın, siz arayın."],
  d:["Çok zorlanıyorsa alanı küçültün."]},
 {c:"b19",a:"dikkat",t:"Beş dakikalık iş",min:48,max:84,dk:10,
  g:"Başladığı işi bitirme alışkanlığı.",
  m:["Kum saati ya da zamanlayıcı"],
  s:["Küçük bir iş seçin: 6 çorabı eşleştirmek.","Zamanlayıcıyı kurun.","Bitince birlikte bakın, sonuca değil sürece bakın."],
  d:["İş gerçekten kısa olsun; bitmeyen iş motivasyonu düşürür."]},

 {c:"b20",a:"kaba",t:"Hayvan yürüyüşü",min:30,max:72,dk:10,
  g:"Denge, güç ve beden farkındalığı.",
  m:["Yok"],
  s:["Ayı gibi yürüyün, kurbağa gibi zıplayın, yengeç gibi yan gidin.","Odanın bir ucundan diğerine geçin.","Hayvanı o seçsin."],
  d:["Okul dönüşü gerginlik varsa önce hareket, sonra sohbet."]},
 {c:"b21",a:"kaba",t:"Balon havada",min:30,max:84,dk:10,
  g:"El-göz koordinasyonu ve takip.",
  m:["Balon"],
  s:["Balonu yere düşürmeden havada tutun.","Sadece elin tersiyle, sonra sadece kafayla deneyin.","Birlikte sayın."],
  d:["Balon patlayabilir; parçalarını hemen toplayın."]},
 {c:"b22",a:"kaba",t:"Yastık parkuru II",min:42,max:84,dk:15,
  g:"Sıralı hareket planlama ve denge.",
  m:["Yastık","İp","Sandalye"],
  s:["Üç istasyonlu bir parkur kurun: tırman, geç, zıpla.","Sırayı sözlü tekrar etsin, sonra uygulasın.","Parkuru o yeniden tasarlasın."],
  d:["Sırayı hatırlaması dikkat için de çalışır."]},

 {c:"b23",a:"bilis",t:"Örüntü treni",min:48,max:84,dk:12,
  g:"Örüntü kurma ve devam ettirme.",
  m:["İki tür nesne (kapak, blok)"],
  s:["Basit bir dizi kurun: kapak-blok-kapak.","Devamını getirsin.","Sonra kendi örüntüsünü kursun, siz devam edin."],
  d:["İki öğeyle başlayın, kolaylaşınca üçe çıkın."]},
 {c:"b24",a:"bilis",t:"Mutfak sayımı",min:36,max:72,dk:10,
  g:"Sayma ile nesne sayısını eşleştirmek.",
  m:["Çatal, kaşık, tabak"],
  s:["Sofrayı birlikte kurun: “Kaç kişiyiz? Kaç tabak lazım?”","Sayarak alsın.","Eksik çıkarsa birlikte sayıp bulun."],
  d:["Sayıları ezberletmek değil, nesneyle eşleştirmek önemli."]},
 {c:"b25",a:"bilis",t:"Gölge eşleştirme",min:42,max:72,dk:12,
  g:"Görsel algı ve şekil-zemin ayrımı.",
  m:["Oyuncaklar","Kâğıt","Kalem"],
  s:["Oyuncakların etrafını kâğıda çizin.","Her oyuncağı kendi gölgesine yerleştirsin.","Sayıyı artırarak zorlaştırın."],
  d:["Okula hazırlıkta görsel algı için iyi bir temeldir."]},
 {c:"b26",a:"bilis",t:"Dün-bugün-yarın panosu",min:54,max:84,dk:10,
  g:"Zaman kavramı ve günü anlatma.",
  m:["Kâğıt","Kalem"],
  s:["Üç sütun çizin.","Her akşam bugüne bir şey çizsin.","Sabah “dün ne yaptık?” diye bakın."],
  d:["Çizimin güzelliği değil, hatırlaması önemli."]},

 {c:"b27",a:"ozbakim",t:"Sabah sıra tablosu",min:42,max:84,dk:15,
  g:"Sabah rutinini bağımsız yürütmek.",
  m:["Kâğıt","Kalem","Buzdolabı mıknatısı"],
  s:["Sabahın 4 adımını birlikte çizin: kalk, giyin, kahvaltı, çanta.","Tabloyu göz hizasına asın.","Her adımda kendisi işaretlesin."],
  d:["Hatırlatmayı siz değil tablo yapsın; bu bağımsızlığı büyütür."]},
 {c:"b28",a:"ozbakim",t:"Düğme tahtası",min:48,max:84,dk:12,
  g:"Giyinme becerisini giysiden bağımsız çalışmak.",
  m:["Eski bir gömlek","Karton"],
  s:["Gömleği kartona gerin.","Oturarak düğmeleri açıp kapatsın.","Sonra üstündeyken deneyin."],
  d:["Sabah acelesinde değil, sakin bir vakitte çalışın."]},
 {c:"b29",a:"ozbakim",t:"Kendi suyum",min:36,max:72,dk:8,
  g:"Bağımsızlık ve kontrollü hareket.",
  m:["Küçük sürahi","Bardak","Havlu"],
  s:["Az su koyduğunuz sürahiyi ona verin.","Kendi bardağına doldursun.","Dökülürse havluyu o alsın."],
  d:["Dökülmek öğrenmenin parçası; temizliği birlikte yapın."]},
 {c:"b30",a:"ozbakim",t:"Akşam çanta kontrolü",min:48,max:84,dk:8,
  g:"Sorumluluk ve eşyalarını yönetme.",
  m:["Okul çantası"],
  s:["Çantayı boşaltsın, içindekileri sayın.","Yarın için gerekenleri o koysun.","Kapağı kapatmak son adım olsun."],
  d:["Unuttuğu bir şey olursa müdahale etmeyin; sonucu görmek öğretir."]},

 {c:"b31",a:"oyun",t:"Kutu ev",min:30,max:72,dk:20,
  g:"Hayali oyun ve mekân kurma.",
  m:["Büyük karton kutu","Boya"],
  s:["Kutuya kapı ve pencere açın.","Birlikte boyayın.","İçinde oynayacağı senaryoyu o kursun."],
  d:["Kendi başına oynamak istediğinde çekilin; yalnız oyun da değerlidir."]},
 {c:"b32",a:"oyun",t:"Doktor çantası",min:36,max:72,dk:15,
  g:"Korkulan durumları oyunla işlemek.",
  m:["Oyuncak doktor seti ya da bant, pamuk"],
  s:["Peluşu muayene etsin.","Siz hasta olun, korkunuzu dile getirin.","Rolleri değiştirin."],
  d:["Okula dair korkular da bu oyunda çıkabilir; dinleyin."]},
 {c:"b33",a:"oyun",t:"Kurallı zar oyunu",min:54,max:84,dk:15,
  g:"Kurala uyma ve kaybetmeyi taşıma.",
  m:["Zar","Kâğıttan basit bir yol"],
  s:["10 kareli bir yol çizin.","Sırayla zar atıp ilerleyin.","Oyun bitince kim kazandı diye konuşun."],
  d:["Kaybedince üzülmesi normal; duyguyu adlandırın, oyunu bitirmeyin."]},

 {c:"b34",a:"ince",t:"Yıldız çizgileri",min:60,max:84,dk:10,
  g:"Okula hazırlıkta kalem kontrolü.",
  m:["Kâğıt","Kalem"],
  s:["Sayfaya noktalar koyun.","Noktaları birleştirsin.","Sonra kendi adının harflerini noktalarla yazıp birleştirsin."],
  d:["Harf öğretmek amaç değil; kalem kontrolü çalışılıyor."]},
 {c:"b35",a:"dikkat",t:"Ne değişti? (zor sürüm)",min:60,max:84,dk:10,
  g:"Görsel dikkat ve çalışma belleği.",
  m:["8-10 küçük nesne","Örtü"],
  s:["Nesneleri dizin, 15 saniye baksın.","Bir tanesini değiştirin ya da yer değiştirin.","Ne değişti diye sorun."],
  d:["Okula hazırlık döneminde dikkat süresi için iyi bir ölçü."]},
 {c:"b36",a:"sosyal",t:"Sınıf kuralları panosu",min:54,max:84,dk:15,
  g:"Grup kurallarını anlamak ve sahiplenmek.",
  m:["Kâğıt","Kalem"],
  s:["Okuldaki kuralları hatırlamaya çalışın.","Her kuralı bir resimle çizin.","Evde de üç kural belirleyip asın."],
  d:["Kuralları o söylesin; yazdıran siz olun."]}
];
const ACTS=[...ACTS_BASE,...ACTS_EXTRA];

/* ================= OKUL OLGUNLUĞU (ilkokula hazırlık) =================
   "Hazır / hazır değil" kararı verilmez; yalnızca üç başlıkta tablo çıkarılır. */
const READY=[
 {c:"dikkat", t:"Dikkat", i:["Bir masa çalışmasında 10-15 dakika kalıyor",
   "Dikkati dağıldığında işe geri dönebiliyor","Başladığı işi bitiriyor"]},
 {c:"yonerge",t:"Yönerge takibi", i:["Üç adımlı yönergeyi tek seferde uyguluyor",
   "Sınıfa verilen toplu yönergeyi üzerine alıyor","Yönergeyi anlamadığında soru soruyor"]},
 {c:"dil",    t:"Dil ve anlatım", i:["Yaşadığı bir olayı sırasıyla anlatıyor",
   "Sorulara tam cümlelerle cevap veriyor","Konuşması herkes tarafından anlaşılıyor"]},
 {c:"ince",   t:"İnce motor", i:["Kalemi üç parmakla tutuyor","Makasla çizgi üzerinde kesiyor",
   "Adını yazmaya çalışıyor"]},
 {c:"gorsel", t:"Görsel algı", i:["Benzer şekilleri ayırt ediyor","Basit bir şekli kopyalıyor",
   "Bir sayfadaki aynı simgeleri bulup işaretliyor"]},
 {c:"sayi",   t:"Temel sayı ve kavram", i:["1-10 sayıp nesne sayısıyla eşleştiriyor",
   "Az-çok, büyük-küçük karşılaştırması yapıyor","Temel şekilleri ve renkleri adlandırıyor"]},
 {c:"sosyal", t:"Sosyal beceriler", i:["Arkadaşıyla anlaşmazlığı konuşarak çözmeye çalışıyor",
   "Gruba katılmak için uygun bir yol deniyor","Yetişkinden uygun biçimde yardım istiyor"]},
 {c:"duygu",  t:"Duygusal düzenleme", i:["Hayal kırıklığında kısa sürede toparlanıyor",
   "Öfkelendiğinde sakinleşme yolu deniyor","Beklemesi gerektiğinde kendini oyalayabiliyor"]},
 {c:"ozbakim",t:"Öz bakım", i:["Tuvaletini bağımsız yapıyor","Kıyafetini kendi giyip çıkarıyor",
   "Yemeğini bağımsız yiyor"]},
 {c:"sorumluluk",t:"Sorumluluk", i:["Eşyalarını tanıyor ve topluyor","Kendi çantasını hazırlıyor",
   "Verilen küçük görevi hatırlayıp yapıyor"]},
 {c:"grup",   t:"Grup içinde hareket", i:["Sırasını bekliyor","Grupla birlikte yer değiştiriyor",
   "Toplu etkinlikte kendi yerini koruyor"]}];
const READY_SCALE=["Henüz başlamadı","Desteğe ihtiyacı var","Gelişiyor","Rahatça yapıyor"];
